### ISSUE TITLE
Install should use vendored ruby or warn user if `irb` is not present

### ISSUE THREAD

**Issue by dharmab** [Linuxbrew/install#50]
`install.sh` currently only checks if `ruby` is present, but Linuxbrew also requires `irb` which is not guaranteed to be present (https://github.com/Linuxbrew/brew/issues/931).

The installer script should either use a vendored ruby in this case, or warn the user that irb is required.

**Comment by sjackman** [comment]
I believe that `irb` should only really be required by the `brew irb` command. It's a bug that `brew` crashes if `irb` is not otherwise available. Would you like to take a stab at fixing it? Here's the problematic line:
https://github.com/Homebrew/brew/blob/a75a8c69b39aa9584c299d37826a1700256e8ab8/Library/Homebrew/debrew/irb.rb#L1

**Comment by sjackman** [comment]
This repository is deprecated. It has been merged into Homebrew/install.
