### ISSUE TITLE
Installer does not fall back to non-sudo installation

### ISSUE THREAD

**Issue by kitmonisit** [Linuxbrew/install#53]
A run of the Linuxbrew install command promises to fallback to `$HOME/.linuxbrew`. But it does not. I am on a RHEL6 machine. Could it be that the `sudo` test in the install script gives a false positive?

    $ sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"

The output is:

```
==> This script will install:
/home/linuxbrew/.linuxbrew/bin/brew
/home/linuxbrew/.linuxbrew/share/doc/homebrew
/home/linuxbrew/.linuxbrew/share/man/man1/brew.1
/home/linuxbrew/.linuxbrew/share/zsh/site-functions/_brew
/home/linuxbrew/.linuxbrew/etc/bash_completion.d/brew
/home/kmonisit/.cache/Homebrew/
/home/linuxbrew/.linuxbrew/Homebrew
==> The following new directories will be created:
/home/linuxbrew/.linuxbrew/bin
/home/linuxbrew/.linuxbrew/etc
/home/linuxbrew/.linuxbrew/include
/home/linuxbrew/.linuxbrew/lib
/home/linuxbrew/.linuxbrew/sbin
/home/linuxbrew/.linuxbrew/share
/home/linuxbrew/.linuxbrew/var
/home/linuxbrew/.linuxbrew/opt
/home/linuxbrew/.linuxbrew/share/zsh
/home/linuxbrew/.linuxbrew/share/zsh/site-functions
/home/linuxbrew/.linuxbrew/Cellar
/home/linuxbrew/.linuxbrew/Caskroom
/home/linuxbrew/.linuxbrew/Homebrew
/home/linuxbrew/.linuxbrew/Frameworks

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir -p /home/linuxbrew/.linuxbrew
[sudo] password for kmonisit:
Sorry, try again.
[sudo] password for kmonisit:
Sorry, try again.
[sudo] password for kmonisit:
Sorry, try again.
```

**Comment by sjackman** [comment]
Here's the relevant code:
https://github.com/Linuxbrew/install/blob/7d3b60c1e3dc1efcf902d1da932639f517813221/install#L94-L99

What does the following output:
```sh
sudo -v
echo $?
sudo -l mkdir
echo $?
```

**Comment by sjackman** [comment]
If all else fails, you can try these alternative installation instructions: https://docs.brew.sh/Linuxbrew#alternative-installation

**Comment by sjackman** [comment]
This PR (in progress) was meant to address this issue: https://github.com/Linuxbrew/install/pull/47

**Comment by kitmonisit** [comment]
```
$ sudo -v
$ echo $?
0
$ sudo -l mkdir 
~❯ echo $?
1
```

So `sudo -l mkdir` throws a false positive as far as the installer is concerned?

**Comment by sjackman** [comment]
`sudo -v` is saying that you do have `sudo` access, without needing a password. It appears to be wrong though, because `sudo -l mkdir` is saying that you do not have `sudo` access. Do you have `sudo` access?

**Comment by kitmonisit** [comment]
No I do not have `sudo` access.

**Comment by sjackman** [comment]
For now then, use the alternative installation instructions: https://docs.brew.sh/Linuxbrew#alternative-installation
PR #47 should hopefully address this issue when it's merged.

**Comment by sjackman** [comment]
PR https://github.com/Linuxbrew/install/pull/47 has been merged. The usual installation instructions should work for you now. Would you be able to test it for us?

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `util-linux`. If it's an option for you, you could open a ticket with your information systems department to ask that they create a `linuxbrew` role account with home directory `/home/linuxbrew`.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below. On macOS the default installation directory is `/usr/local`. On Linux the default installation directory is `/home/linuxbrew/.linuxbrew`.

+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by kitmonisit** [comment]
> PR #47 has been merged. The usual installation instructions should work for you now. Would you be able to test it for us?

I just tested this on a fresh CentOS 6.10 virtual machine. It will now fall back to `$HOME/.linuxbrew` installation.

**Comment by sjackman** [comment]
Glad to hear it. Thanks for following up, Kit.

**Comment by hwalinga** [comment]
Somehow this does not work for me. I don't know if I am just doing something wrong, or that it is because I have something different with my machine, or that some other commit made it stopped working. 

Executing:

```
 sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
```

Error:

```
Failed during: /usr/bin/sudo /bin/mkdir -p /home/linuxbrew/.linuxbrew
```

Tried both pressing return three times and C-D.

MX Linux 19 (Debian 10).

**Comment by sjackman** [comment]
What's the output of running `/usr/bin/sudo /bin/mkdir -p /home/linuxbrew/.linuxbrew` interactively at the command line?

**Comment by hwalinga** [comment]
Well, first I get:
```
[sudo] password for hielke: 
```

Then I hit C-D

and get:

```
sudo: no password was provided
```

Exit code 1.

What do you check for it to fail?

**Comment by hwalinga** [comment]
I think I understand what is happening. You are checking `sudo -l mkdir` to check if I am allowed to run sudo. I am allowed to run sudo, but I don't want to install linuxbrew with the sudo rights. (I just don't like that.) 

So, it seems almost like a design choice that whenever a user has sudo rights, but decides to not grant linuxbrew the sudo rights it just refused to install. Is this indeed intended?

**Comment by hwalinga** [comment]
So, I looked at the code and some related issues. It seems there are two tests `sudo -l` and `sudo -v` and it seems that picking one will not cover all cases, as sometimes the on succeeds when it should not and sometimes the other succeeds when it should not. 

I would therefor suggest to use both and only skip the prompt about the different ways of installation if both succeed. If one or the other fails, it should prompt for the password with the different options. 

If you think this is a good idea. I can see if I can make a PR.

**Comment by sjackman** [comment]
> I am allowed to run sudo, but I don't want to install linuxbrew with the sudo rights. (I just don't like that.)

I strongly recommend installing Homebrew in its default installation directory of `/home/linuxbrew/.linuxbrew`. You can create the directory `/home/linuxbrew` yourself if you like, and ensure that your current user has permissions to write to it, and then the installer will not need `sudo` to run. The following is copy-pasted informational text as to why the standard installation directory is preferred.

Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `util-linux`.
Another possible workaround for you is `brew install --force-bottle util-linux`, but no promises.

If it's an option for you, you could open a ticket with your information systems department to ask that they create a `linuxbrew` role account with home directory `/home/linuxbrew`.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below. On macOS the default installation directory is `/usr/local`. On Linux the default installation directory is `/home/linuxbrew/.linuxbrew`.

+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by hwalinga** [comment]
It's just a matter of principle. It's good to be informed, but just give a user a choice. 

I have linuxbrew installed on my own pc and on a shared server. I don't have sudo rights on the shared server, so I install in the home directory. While I do have sudo rights on my own pc, I don't want to deviate from the way I organize my stuff on the server. If there is a difference I might face unexpected surprises if something worked on my pc, but not on the server. 

I don't mind if you decide differently and keep it the way it is now, but this is just my perspective.

**Comment by sjackman** [comment]
Pressing Ctrl-D at the `sudo` password prompt is meant to install in the user's home directory. If that doesn't work for you, and if you're able to find a fix, a PR to fix it would be most welcome.
